export const CHECK_USER_AUTH: 'CHECK_USER_AUTH' = 'CHECK_USER_AUTH';
export const CHECK_USER_AUTH_SUCCESS: 'CHECK_USER_AUTH_SUCCESS' = 'CHECK_USER_AUTH_SUCCESS';
export const CHECK_USER_AUTH_FAILED: 'CHECK_USER_AUTH_FAILED' = 'CHECK_USER_AUTH_FAILED';

export const LOGOUT: 'LOGOUT' = 'LOGOUT';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const REGISTER: 'REGISTER' = 'REGISTER';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const AUTHORIZATION: 'AUTHORIZATION' = 'AUTHORIZATION';
export const AUTHORIZATION_SUCCESS: 'AUTHORIZATION_SUCCESS' = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILED: 'AUTHORIZATION_FAILED' = 'AUTHORIZATION_FAILED';

export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const CHECK_EMAIL_EXIST: 'CHECK_EMAIL_EXIST' = 'CHECK_EMAIL_EXIST';
export const CHECK_EMAIL_EXIST_SUCCESS: 'CHECK_EMAIL_EXIST_SUCCESS' = 'CHECK_EMAIL_EXIST_SUCCESS';
export const CHECK_EMAIL_EXIST_FAILED: 'CHECK_EMAIL_EXIST_FAILED' = 'CHECK_EMAIL_EXIST_FAILED';

export const GET_USER_INFO: 'GET_USER_INFO' = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS' = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED' = 'GET_USER_INFO_FAILED';

export const UPDATE_USER_INFO: 'UPDATE_USER_INFO' = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS' = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILED: 'UPDATE_USER_INFO_FAILED' = 'UPDATE_USER_INFO_FAILED';

export const CHANGE_FORGOT_PASSWORD_EMAIL: 'FORGOT_PASSWORD_CHANGE_EMAIL' = 'FORGOT_PASSWORD_CHANGE_EMAIL';

export const REMIND_PASSWORD: 'REMIND_PASSWORD' = 'REMIND_PASSWORD';